### PR TITLE
Add JSON Output Support for Metrics to MultiVCFAnalyzer

### PR DESCRIPTION
**Pull request by apeltzer**
This adds support for creating a JSON output file for the statistics generated by MultiVCFAnalyzer. It doesn't change anything else.

- JSON output for metadata info
- JSON output for statistics of individual samples

Both have been nested inside a single JSON that we can then parse automatically in MultiQC V1.8 (coming soon hopefully!) to have this properly supported in EAGER2 (nf-core/eager). @jfy133 is currently testing whether the generated JSON file looks fine/sane and once he confirmed here, this is good to go. We will then update the bioconda package, too. 

I've also taken the liberty to add a Gradle Build script so that people without an IDE can simply type `gradle build` and get this built with all dependencies (currently only the Google JSON library).

### CODE REVIEW

**Comment by jfy133** [comment]
I confirm the JSON looks good. Ready to merge.

**Comment by apeltzer** [comment]
Ping @alexherbig !

**Comment by apeltzer** [comment]
Now we only need a new release :-)

**Comment by alexherbig** [comment]
Need to add a few things first.

**Comment by alexherbig** [comment]
Thanks for adding the JSON support, Alex.

**Pull request merged**
